"""Rename 'birthday' column to 'birthdays'

Revision ID: 07b47ee7a621
Revises: 791279dd0760
Create Date: 2024-01-18 15:40:10.179758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b47ee7a621'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthdays', sa.DateTime(), nullable=True))
    op.drop_column('students', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthday', sa.DATETIME(), nullable=True))
    op.drop_column('students', 'birthdays')
    # ### end Alembic commands ###
